
name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install circom
        env:
          RUSTFLAGS: ''
        run: |
          git clone https://github.com/iden3/circom.git ~/circom
          cd ~/circom
          cargo build
          cargo install --path circom
          cd -
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
